//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExifAnalyzer.Common.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExifAnalyzer.Common.Localisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to analyze and press the &quot;Start&quot; button.
        /// </summary>
        public static string DirectoryDescription {
            get {
                return ResourceManager.GetString("DirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action program.
        /// </summary>
        public static string ExposureActionProgram {
            get {
                return ResourceManager.GetString("ExposureActionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture priority.
        /// </summary>
        public static string ExposureAperturePriority {
            get {
                return ResourceManager.GetString("ExposureAperturePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative program.
        /// </summary>
        public static string ExposureCreativeProgram {
            get {
                return ResourceManager.GetString("ExposureCreativeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape mode.
        /// </summary>
        public static string ExposureLandscapeMode {
            get {
                return ResourceManager.GetString("ExposureLandscapeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string ExposureManual {
            get {
                return ResourceManager.GetString("ExposureManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal program.
        /// </summary>
        public static string ExposureNormalProgram {
            get {
                return ResourceManager.GetString("ExposureNormalProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Defined.
        /// </summary>
        public static string ExposureNotDefined {
            get {
                return ResourceManager.GetString("ExposureNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait mode.
        /// </summary>
        public static string ExposurePortraitMode {
            get {
                return ResourceManager.GetString("ExposurePortraitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter priority.
        /// </summary>
        public static string ExposureShutterPriority {
            get {
                return ResourceManager.GetString("ExposureShutterPriority", resourceCulture);
            }
        }
    }
}
